const search=document.querySelector('#search'), filter=document.querySelector('#topic-filter');
if(search&&filter){const cards=[...document.querySelectorAll('.day-card')],groups=[...document.querySelectorAll('.course-group')];function update(){const query=search.value.trim().toLowerCase();let count=0;for(const card of cards){const show=(!query||card.dataset.search.includes(query))&&(!filter.value||card.dataset.group===filter.value);card.hidden=!show;if(show)count++;}for(const group of groups)group.hidden=![...group.querySelectorAll('.day-card')].some(c=>!c.hidden);document.querySelector('#result-count').textContent=`${count} of 63 days`;document.querySelector('#empty').hidden=count>0;}search.addEventListener('input',update);filter.addEventListener('change',update);}

const siteHeader=document.querySelector('.site-header');
if(siteHeader){const sizeHeader=()=>document.documentElement.style.setProperty('--site-header-height',`${siteHeader.offsetHeight}px`);sizeHeader();new ResizeObserver(sizeHeader).observe(siteHeader);}
const daySearch=document.querySelector('#day-search'),dayList=document.querySelector('.day-scroll');
if(daySearch&&dayList){const days=[...dayList.querySelectorAll('a')];daySearch.addEventListener('input',()=>{const query=daySearch.value.trim().toLowerCase();let matches=0;for(const day of days){day.hidden=!day.textContent.toLowerCase().includes(query);if(!day.hidden)matches++;}document.querySelector('#day-empty').hidden=matches>0;});const active=dayList.querySelector('[aria-current="page"]');if(active)dayList.scrollTop=active.offsetTop-dayList.offsetTop-dayList.clientHeight/2+active.clientHeight/2;}
const commandSearch=document.querySelector('#command-search');
if(commandSearch){const entries=[...document.querySelectorAll('.command-entry')],sections=[...document.querySelectorAll('.command-section')];commandSearch.addEventListener('input',()=>{const query=commandSearch.value.trim().toLowerCase();let matches=0;for(const entry of entries){entry.hidden=!entry.dataset.commandSearch.includes(query);if(!entry.hidden)matches++;}for(const section of sections)section.hidden=![...section.querySelectorAll('.command-entry')].some(e=>!e.hidden);document.querySelector('#command-count').textContent=`${matches} of ${entries.length} commands`;document.querySelector('#command-empty').hidden=matches>0;});}
const sidebarDetails=document.querySelector('.course-sidebar details');
if(sidebarDetails){const mobile=matchMedia('(max-width:900px)');const sizeSidebar=()=>{sidebarDetails.open=!mobile.matches;};sizeSidebar();mobile.addEventListener('change',sizeSidebar);}
